### ISSUE TITLE
Phabricator

### ISSUE THREAD

**Issue by schmelling** [schmelling/freies_wissen_feedback#1]
Sollen wir alles auf [Wikimedia's Phabricator](https://phabricator.wikimedia.org) verlagern?

**Comment by Eryops1** [comment]
Ich kenne den Phabricator noch nicht, denke aber für einfache Textdokumente mit links etc. ist das Repo hier ok (und für mich super zum GitHub üben).

**Comment by crupprecht** [comment]
Danke Nic und Daniel für die Initiative!

**Comment by rubenarslan** [comment]
+1 Für Github
